"""add session expiry

Revision ID: 2a3edd51b78f
Revises: 70abf3e4f946
Create Date: 2026-10-05 00:27:45.809556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic.
revision: str = '2a3edd51b78f'
down_revision: Union[str, Sequence[str], None] = '70abf3e4f946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_sessions', sa.Column('expires_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_sessions', 'expires_at')
    # ### end Alembic commands ###